[tools]
bat = "latest"
bun = "1.4.0"
crush = "latest"
delta = "latest"
deno = "2.9.6"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "1.27.1"
jq = "latest"
just = "latest"
lazygit = "latest"
neovim = "0.12.5"
node = "26.8.1"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:neovim" = "latest"
"npm:typescript" = "latest"
"npm:vue-tsc" = "latest"
opencode = "latest"
pi = "latest"
python = "3.14.7"
ripgrep = "latest"
starship = "latest"
uv = "latest"
yazi = "latest"
zig = "0.16.0"
zls = "0.16.0"
zoxide = "latest"
